kind: pipeline
name: default
pipeline:
  build:
    image: alpine
    commands: echo -n "this-is-a-test" > .tags
  test:
    image: alpine
    commands: echo -n "this-is-a-test" > .tags
steps:
  - name: write
    image: alpine
    commands:
      - echo -n "this-is-a-test" > .tags
